### ISSUE TITLE
Reset a Masked-Edittext

### ISSUE THREAD

**Issue by bsysop** [pinball83/Masked-Edittext#1]
Hi dude, first say you thanks about your great work!.

Second, i want to programmatically clear a Masked-Edittext, let me show you a example:

`maskedEditText1 = new MaskedEditText(this, "(**) **** - *****", "*", getResources().getDrawable(R.drawable.ic_account_circle),
                new MaskedEditText.MaskIconCallback() {
                    @Override
                    public void onIconPushed() {
                        maskedEditText1.setText("");
                        System.out.println("Icon pushed");
                    }
                });
        maskedEditText1.setInputType(InputType.TYPE_CLASS_NUMBER);`

But this give me a error when click in the button.

Third question, i try to set a "Hint" but looks this not works, i wrong?

Thank you very much!.

**Comment by pinball83** [comment]
Hi I slightly improve library you can update library and do following

1) Just add in your callback method this code:

``` java
final MaskedEditText maskedEditText1 = new MaskedEditText(this,
                "(**) **** - *****",
                "*",
                getResources().getDrawable(R.drawable.ic_account_circle));

maskedEditText1.setMaskIconCallback(new MaskedEditText.MaskIconCallback() {
                    @Override
                    public void onIconPushed() {
//input number of space symbols as much as your mask consist input symbols, in your case it will 11 spaces
                        System.out.println("Icon pushed");
                        maskedEditText1.setMaskedText("           ");
                    }

```

2) Hint will not show because we have already inserted text, its a feature of this library

**Comment by bsysop** [comment]
This is really great, thank you very much @pinball83 
Good job.

**Comment by ulaserdegor** [comment]
maskedEditText1.setMaskedText("           ");
it's not working . @pinball83

**Comment by jailson-developer** [comment]
MaskedText (""); It works, however if your text was eg 123456 you have to replace the numbers with empty space, in this case maskedEditText1.setMaskedText ("______");  (Replace ______ with empty)

MaskedText.setMaskedText(new String(new char[MaskedText.getUnmaskedText().length()]).replace("\0", " "));
