### ISSUE TITLE
Manifest Merger Failed

### ISSUE THREAD

**Issue by zsperske** [pinball83/Masked-Edittext#2]
Error:Execution failed for task ':main:MyApp:processProdDebugManifest'.

> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:58:9-36
>     is also present at [com.github.pinball83:masked-edittext:1.0.2] AndroidManifest.xml:12:9-35 value=(true).
>     Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:11:5-13:39 to override.

You should probably not include this attribute.

**Comment by pinball83** [comment]
Fix manifest and update library in maven central
