### ISSUE TITLE
how to hide text and show hint before we focus ..?

### ISSUE THREAD

**Issue by Pareshoct7** [pinball83/Masked-Edittext#24]
I want to show hint in edit text and when user start to typing any thing then only masked characters are appear and if edittext is empty show the hint

**Comment by stijnster** [comment]
+1

**Comment by renatacmn** [comment]
+1

**Comment by thalisvilela** [comment]
+1

**Comment by pinball83** [comment]
Thank you for your feedback I want to add this feature in 1.1.0 version, which will be next I hope

**Comment by saddahussain** [comment]
@pinball83 this feature still hasn't been added.
