### ISSUE TITLE
Bug When try to get UnmaskedText

### ISSUE THREAD

**Issue by Pahanuch** [pinball83/Masked-Edittext#25]
java.lang.IndexOutOfBoundsException: charAt: 17 >= length 17

**Comment by voronnenok** [comment]
⬆️

**Comment by ekrivenja** [comment]
Yes, also faced with this issue.

> java.lang.IndexOutOfBoundsException: 
  at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:116)
  at com.github.pinball83.maskededittext.MaskedEditText.getUnmaskedText(MaskedEditText.java:198)

`public String getUnmaskedText() { 

        Editable text = super.getText();
        if (mask != null && !mask.isEmpty()) {
            Editable unMaskedText = new SpannableStringBuilder();
            for (Integer index : listValidCursorPositions) {
                if (text != null) {
                    //FIXME: this line throws the exception
                    unMaskedText.append(text.charAt(index));
                }
            }
            if (format != null && !format.isEmpty())
                return formatText(unMaskedText.toString(), format);
            else
                return unMaskedText.toString().trim();
        }
        return text.toString().trim();
    }`

**Comment by pinball83** [comment]
Hi, thank you for you feedback, please try use new version, I merge PR with several hotfixes it must help
