### ISSUE TITLE
Add badge for android-gems.com

### ISSUE THREAD

**Issue by liaohuqiu** [pinball83/Masked-Edittext#3]
Added badge for android-gems: http://www.android-gems.com/lib/pinball83/Masked-Edittext , it looks like this:

[![Android Gems](http://www.android-gems.com/badge/pinball83/Masked-Edittext.svg?branch=master)](http://www.android-gems.com/lib/pinball83/Masked-Edittext)

```
[![Android Gems](http://www.android-gems.com/badge/pinball83/Masked-Edittext.svg?branch=master)](http://www.android-gems.com/lib/pinball83/Masked-Edittext)
```

**Comment by pinball83** [comment]
Added bage
