### ISSUE TITLE
EditText removes mask symbols if a user input non-digit symbols and then are crashed

### ISSUE THREAD

**Issue by skatset** [pinball83/Masked-Edittext#7]
On several devices the keyboard contains ',' '.' and '-' symbols even if I specify "number" input type.

When I input this symbols then your EditText removes from mask one symbol. If I repeat this procedure then the EditText removes all symbols from mask and then crashes.

There are my code example. I think that presence of "+7" is the root of problem:

```
       <com.github.pinball83.maskededittext.MaskedEditText
                android:id="@+id/phone"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:hint="@string/prompt_phone"
                android:inputType="phone"
                android:maxLines="1"
                android:singleLine="true"
                app:mask="+7 (***) ***-**-**"
                app:notMaskedSymbol="*"
                app:maskIconColor="@color/colorPrimary"
                />
```

**Comment by drakmail** [comment]
Have same issue when I'm input `,` char in input with type `number`

**Comment by AlexanderGarmash** [comment]
Have same issue
